uint32 command_id
uint8 opcode
int32 argument
builtin_interfaces/Duration ack_timeout
---
uint8 COMPLETED=0
uint8 CANCELED=1
uint8 SAFE_STOP=2
uint8 DEVICE_FAULT=3
uint8 outcome
uint16 error_code
string message
---
uint8 SENDING=1
uint8 WAITING_ACK=2
uint8 RETRYING=3
uint8 STOPPING=4
uint8 state
uint8 retry_count
